export const JobActions = {
  CREATE_JOB: 'CREATE_JOB',
  RECIVED_PACKAGE: 'RECIVED_PACKAGE',
  SEND_PACKAGE_TO_SAT: 'SEND_PACKAGE_TO_SAT',
  PACKAGE_RECEIVED_FROM_SAT: 'PACKAGE_RECEIVED_FROM_SAT',
  PACKAGE_ERROR: 'PACKAGE_ERROR',
  PACKAGE_SUCCESS: 'PACKAGE_SUCCESS',
  PACKAGE_CANCELLED: 'PACKAGE_CANCELLED',
  PACKAGE_ACCEPTED: 'PACKAGE_ACCEPTED',
  PACKAGE_PENDING: 'PACKAGE_PENDING',
  CONSULTING_PACKAGE: 'CONSULTING_PACKAGE',
} as const;

export type JobAction = (typeof JobActions)[keyof typeof JobActions];
